# Enable mouse support
setw -g mouse on

set -g base-index 1
setw -g pane-base-index 1

# Kill the tmux session when the terminal is closed
# set-option -g destroy-unattached on

# Set new panes to open in current directory
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"

# Yank selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection
# Begin selection in copy mode.
bind-key -T copy-mode-vi 'v' send -X begin-selection
# Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle

set -g @floating_scratch_term 'M-i'
set -g @floating_scratch_to_active_win 'M-h'
set -g @floating_scratch_to_win 'M-l'
set -g @floating_active_pane_to_scratch 'M-m'

# # Enable mouse scrolling
# set -g mouse on
#
# # Scroll up/down using Ctrl + Arrow keys
# bind -n C-Up if-shell -F "#{pane_in_mode}" "send-keys Up" "copy-mode -e; send-keys Up"
# bind -n C-Down if-shell -F "#{pane_in_mode}" "send-keys Down" "copy-mode -e; send-keys Down"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @emulate-scroll-for-no-mouse-alternate-buffer "on"
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'catppuccin/tmux#v2.1.1'
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @plugin 'lloydbond/tmux-floating-terminal'

run '~/.tmux/plugins/tpm/tpm'
